# Generated by Django 4.0 on 2021-12-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('insta', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('articul', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('pending', models.BooleanField(default=False)),
                ('in_transit', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
            ],
        ),
    ]
