# Generated by Django 4.0 on 2021-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, verbose_name='Фио')),
                ('insta', models.CharField(max_length=50, verbose_name='Инстаграм')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('articul', models.CharField(max_length=255, verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('pending', models.BooleanField(default=False)),
                ('in_transit', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
