# Generated by Django 4.0 on 2021-12-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='articul',
            field=models.CharField(max_length=255, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.CharField(max_length=255, verbose_name='Фио'),
        ),
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='insta',
            field=models.CharField(max_length=50, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='order',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.IntegerField(verbose_name='Размер'),
        ),
    ]
